#!/bin/bash

pid="$(cat $HOME/.config/expo/running)"

if [[ $pid == "" ]]; then
 tint2 -c $HOME/.config/tint2/OSD.tint2rc & echo $! > $HOME/.config/expo/running
else
 kill $pid
 truncate -s 0 $HOME/.config/expo/running
fi
